#!/bin/sh

if [[ "$OSTYPE" == "darwin"* ]]; then
	clang++ -O2 -o test -ggdb -std=c++11 test.cpp tsf.cpp uberlog.cpp
	clang++ -O2 -o uberlogger -ggdb -std=c++11 uberlogger.cpp tsf.cpp uberlog.cpp
else
	clang++ -O2 -o test -ggdb -std=c++11 test.cpp tsf.cpp uberlog.cpp -lrt
	clang++ -O2 -o uberlogger -ggdb -std=c++11 uberlogger.cpp tsf.cpp uberlog.cpp -lrt
fi